import { initCarousel }     from "./modules/components/carousel.js";
import { initLogo }         from "./modules/components/logo.js";
import { initBurgerMenu }   from "./modules/components/menu.js";
import { initIndexScroll }  from "./modules/components/indexScroll.js";
import { initTicker }       from "./modules/components/ticker.js";
import { initProjectsGrid } from "./modules/components/projectsGrid.js";
initBurgerMenu();
initCarousel();
initLogo();
initTicker();
initIndexScroll();
initProjectsGrid();